//! Provider-agnostic cognition adapters.
//!
//! A [`Provider`] receives an immutable [`ProviderRequest`] and can only return
//! a structured proposal. It receives neither a runtime projection to mutate,
//! an activity port, nor a kernel commit token. The [`atom_runtime::Runtime`]
//! owns the later perceive/decide/act/observe phases, while consequential work
//! remains subject to its durable effect path and the sovereign kernel.
//!
//! There is deliberately no provider name, transport, clock, or retry policy in
//! this crate. Hermes, OpenClaw, a local model, and a deterministic test double
//! are all injected as implementations of [`Provider`].

#![forbid(unsafe_code)]

use atom_effect::EffectIntent;
use atom_mission::MissionCommand;
use atom_runtime::{ActivityProposal, Cognition, Decision, HoldReason, Perception};

/// Implementation maturity marker.
pub const CRATE_STAGE: &str = "G1-provider-agnostic-cognition-adapter";

/// Immutable, deterministic input supplied to one provider invocation.
///
/// `proposal_id` is generated by the runtime's injected random source. The
/// provider must return a proposal for that identity; it must not invent a new
/// identifier or read a clock.
#[derive(Clone, Copy, Debug)]
pub struct ProviderRequest<'a> {
    /// The runtime's immutable context assembly for this cognition cycle.
    pub perception: &'a Perception,
    /// The deterministic identity assigned by the runtime.
    pub proposal_id: u64,
}

impl<'a> ProviderRequest<'a> {
    /// Creates an invocation request from runtime-owned context.
    #[must_use]
    pub const fn new(perception: &'a Perception, proposal_id: u64) -> Self {
        Self {
            perception,
            proposal_id,
        }
    }
}

/// Model/runtime backend injection point.
///
/// This trait is intentionally total: a provider that cannot produce a safe
/// proposal must return [`ProviderProposal::Hold`]. That keeps the runtime
/// [`Cognition`] interface deterministic and makes failures a proposal rather
/// than an implicit state mutation or side effect.
pub trait Provider {
    /// Produces one structured, non-authoritative proposal.
    fn invoke(&mut self, request: ProviderRequest<'_>) -> ProviderProposal;
}

/// A structured capability invocation proposed by a provider.
///
/// The effect is still only an intent. [`ProviderCognition`] converts this to
/// a runtime [`Decision`]; the runtime persists the intent before an activity
/// can begin, and any consequential mutation still needs the effect/kernel
/// gates downstream.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CapabilityInvocation {
    /// Lifecycle command that the runtime will validate against its projection.
    pub command: MissionCommand,
    /// Declared capability-bound effect intent, not permission to dispatch.
    pub effect: EffectIntent,
}

impl CapabilityInvocation {
    /// Creates a structured capability invocation.
    #[must_use]
    pub fn new(command: MissionCommand, effect: EffectIntent) -> Self {
        Self { command, effect }
    }
}

/// The only outputs a provider can give to the runtime.
///
/// None of these variants carries mutable cognition state, an activity port,
/// or an atom-kernel commit token. Consequently a provider invocation can
/// propose work but cannot directly mutate authoritative state.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProviderProposal {
    /// A non-consequential lifecycle activity proposal.
    Activity {
        /// Command to validate in the runtime.
        command: MissionCommand,
    },
    /// A capability-bound action proposal, still subject to effect/kernel gates.
    Capability(Box<CapabilityInvocation>),
    /// A read-only reconciliation proposal for an existing effect.
    Reconcile {
        /// Effect identity to reconcile.
        effect_id: String,
    },
    /// A safe no-op proposal.
    Hold {
        /// Reason that no action is proposed.
        reason: HoldReason,
    },
}

impl ProviderProposal {
    /// Creates a non-consequential lifecycle activity proposal.
    #[must_use]
    pub const fn activity(command: MissionCommand) -> Self {
        Self::Activity { command }
    }

    /// Creates a capability-bound proposal.
    #[must_use]
    pub fn capability(command: MissionCommand, effect: EffectIntent) -> Self {
        Self::Capability(Box::new(CapabilityInvocation::new(command, effect)))
    }

    /// Creates a terminal safe hold.
    #[must_use]
    pub const fn hold_terminal() -> Self {
        Self::Hold {
            reason: HoldReason::Terminal,
        }
    }

    /// Binds a runtime-assigned proposal identity without applying any state.
    #[must_use]
    pub fn into_decision(self, proposal_id: u64) -> Decision {
        match self {
            Self::Activity { command } => Decision::Act(Box::new(ActivityProposal {
                proposal_id,
                command,
                effect: None,
            })),
            Self::Capability(invocation) => Decision::Act(Box::new(ActivityProposal {
                proposal_id,
                command: invocation.command,
                effect: Some(invocation.effect),
            })),
            Self::Reconcile { effect_id } => Decision::Reconcile {
                proposal_id,
                effect_id,
            },
            Self::Hold { reason } => Decision::Hold {
                proposal_id,
                reason,
            },
        }
    }
}

/// Adapts an injected provider to atom-runtime's provider-free cognition API.
///
/// The adapter owns only the backend's own client state. Authoritative mission
/// and effect state stay inside [`atom_runtime::Runtime`], which passes this
/// adapter immutable [`Perception`] values.
#[derive(Clone, Debug)]
pub struct ProviderCognition<P> {
    provider: P,
}

impl<P> ProviderCognition<P> {
    /// Wraps an injected provider backend.
    #[must_use]
    pub fn new(provider: P) -> Self {
        Self { provider }
    }

    /// Read-only access to the injected provider, useful for audit/testing.
    #[must_use]
    pub fn provider(&self) -> &P {
        &self.provider
    }

    /// Mutable access to backend-local state only.
    ///
    /// This cannot expose runtime cognition state because it is not owned by
    /// the adapter.
    pub fn provider_mut(&mut self) -> &mut P {
        &mut self.provider
    }

    /// Unwraps the injected backend.
    #[must_use]
    pub fn into_provider(self) -> P {
        self.provider
    }
}

impl<P: Provider> Cognition for ProviderCognition<P> {
    fn decide(&mut self, perception: &Perception, proposal_id: u64) -> Decision {
        self.provider
            .invoke(ProviderRequest::new(perception, proposal_id))
            .into_decision(proposal_id)
    }
}
