//! Wire request/response envelopes for the ATOM /v1 API.
//!
//! These types are SDK-side DTOs that match the OpenAPI spec v4.0 exactly.

use std::fmt;

use serde::{Deserialize, Serialize};

use atom_artifact::Artifact;
use atom_claim::{Claim, ClaimId, ProvenanceGraph};
use atom_effect::EffectIntent;

/// Successful health-check response (matches spec: getHealth 200).
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct HealthStatus {
    /// Health status enum.
    pub status: String,
    /// ATOM protocol version this node speaks.
    pub version: String,
    /// Uptime in seconds.
    pub uptime_seconds: u64,
    /// Number of crates linked into the node (sanity check).
    pub crates_loaded: usize,
}

/// Wrapper for submitting an effect intent for kernel authorization.
///
/// The intent is the canonical wire shape; we add only request metadata
/// (id, idempotency key) that is *not* part of the intent itself.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct SubmitEffectRequest {
    /// Client-generated request id; echoed in the response for traceability.
    pub request_id: String,
    /// Idempotency key — sent as `Idempotency-Key` header; same key + same intent MUST return same receipt.
    pub idempotency_key: String,
    /// The intent to authorize and commit.
    #[serde(flatten)]
    pub intent: EffectIntent,
}

/// Opaque receipt from `submit_effect` — confirms authorization + commit without exposing
/// kernel authority types (Authorization, CommitToken) which must remain unforgeable.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct SubmitEffectResponse {
    /// The request id echoed back.
    pub request_id: String,
    /// The idempotency key echoed back.
    pub idempotency_key: String,
    /// The effect that was authorized and committed.
    pub effect_id: String,
    /// Lifecycle state of the effect after commit (from EffectState enum).
    pub state: String,
    /// Grant generation at commit time.
    pub grant_generation: u64,
    /// Whether a commit token was issued (effect is committed).
    pub committed: bool,
}

/// Wrapper for verifying a content-addressed artifact.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct VerifyArtifactRequest {
    /// The artifact (content + provenance + sbom + signature) to verify.
    #[serde(flatten)]
    pub artifact: Artifact,
}

/// Response from `verify_artifact`.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct VerifyArtifactResponse {
    /// `true` iff the artifact verifies end-to-end.
    pub valid: bool,
    /// SHA-256 of the artifact bytes (`sha256:...`).
    pub content_id: String,
    /// If `valid` is false, the structured reason.
    pub failure_reason: Option<String>,
}

/// Response from `get_claim` — returns the claim + its provenance DAG.
///
/// ProvenanceGraph now implements Serialize/Deserialize with validation.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct GetClaimResponse {
    /// The claim itself.
    pub claim: Claim,
    /// The provenance DAG the claim references.
    pub provenance: ProvenanceGraph,
}

/// Request body for `put_claim` — create or replace a claim.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutClaimRequest {
    /// Client-generated id for the claim (idempotent on retry).
    pub claim_id: ClaimId,
    /// The claim to create.
    pub claim: Claim,
}

/// Response from `put_claim` — confirms the claim id that was stored.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutClaimResponse {
    /// The claim id that was persisted.
    pub claim_id: ClaimId,
    /// The state the claim landed in (e.g. `Pending`, `Confirmed`).
    pub state: String,
}

/// RFC 9457 ProblemDetail error envelope returned by /v1.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ProblemDetail {
    /// A URI reference that identifies the problem type.
    pub r#type: String,
    /// A short, human-readable summary of the problem type.
    pub title: String,
    /// The HTTP status code generated by the origin server.
    pub status: u16,
    /// A human-readable explanation specific to this occurrence.
    pub detail: String,
    /// A URI reference that identifies the specific occurrence of the problem.
    pub instance: String,
}

impl fmt::Display for ProblemDetail {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} (status {}): {}",
            self.title, self.status, self.detail
        )
    }
}